url: "https://soocubus.github.io"
robots: noindex

header_pages:
  - cv_rus.md

style: dark

footer: 'contact me via telegram: <a href="https://t.me/the_kuribayashi">@the_kuribayashi</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
