url: "https://modeus-the-lustful-demon.github.io"
robots: noindex

header_pages:
  - cv_rus.md

style: dark

footer: 'contact me via telegram: <a href="https://t.me/soo_cubus">@soo_cubus</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
