url: "https://modeus-the-lustful-demon.github.io"
robots: noindex

header_pages:
  - index.md

style: dark

footer: 'jekyll theme on <a href="https://github.com/b2a3e8/jekyll-theme-console">github</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
